### ISSUE TITLE
Clarify some steps of the release process

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/release-toolkit-gutenberg-mobile#117]
Based on the experience of release wranglers in past releases, we identified some steps of the [Release Checklist](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/blob/trunk/Releasing.md#release-checklist-template) that would be great to clarify in the spirit of avoiding potential mistakes:

### Step - Mark all 4 PRs ready for review and request review from your release wrangler buddy.
In some releases like beta fixes, it's likely that the PRs could have conflicts with `trunk`. In this case, we shouldn't try to solve them by updating with `trunk`, as this will imply introducing new and unexpected changes into the release. We should omit them until the release is integrated into the main apps, and only solve them when we are merging the PRs back to `trunk`.

**Action:** As a clarification on this part, we could add a note in the step explaining the above.

### Step - Create a new gutenberg-mobile GitHub Release. Include a list of changes in the Release description. 
It's not clear how the GitHub release is published. We need to clarify that we publish it via the "Publish release" button. We don't publish it as a pre-release.

**Action:** Expand the step and explain how we publish the GitHub release.

**Comment by derekblank** [comment]
Thanks for creating this issue @fluiddot, I think these would be good additions to add to the Release Checklist. I just want to clarify this step, as I think this is the part where I was getting stuck:

> In some releases like beta fixes, it's likely that the PRs could have conflicts with trunk. In this case, we shouldn't try to solve them by updating with trunk, as this will imply introducing new and unexpected changes into the release. We should omit them until the release is integrated into the main apps, and only solve them when we are merging the PRs back to trunk.

The concept of this makes sense, but I wanted to clarify what "omit" meant here. What would be the steps to omit the conflict here? My understanding is that this means would simply leave the conflicts as-is, and create a second branch where we can resolve the conflicts from `trunk` to verify that the CI will pass. If that is true, at which point would we resolve the conflicts in the first branch?

**Comment by fluiddot** [comment]
> The concept of this makes sense, but I wanted to clarify what "omit" meant here. What would be the steps to omit the conflict here?

There are no specific steps for omitting the conflict, the idea is that we finish the integration of the release into the main apps without addressing the conflicts. Then, after the integration when we merge the release PRs, we'll solve them.

> My understanding is that this means would simply leave the conflicts as-is, and create a second branch where we can resolve the conflicts from `trunk` to verify that the CI will pass.

I'd like to clarify that creating a second branch is optional, in fact, I've rarely seen this in past releases. I mentioned it in case we need it at some point but I wouldn't consider it part of the release process. 

> If that is true, at which point would we resolve the conflicts in the first branch?

As I shared above, the conflicts will be solved after integrating the release into the main apps and merging the release branches:

> **Merge Release Branches**
> Resolve any conflicts with `trunk` and merge the gutenberg PR.

_Extracted from a release checklist._

**Comment by dcalhoun** [comment]
It appears this was added by https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/pull/125. Closing.
