### ISSUE TITLE
gbm CLI checklist includes targeted days of the week

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/release-toolkit-gutenberg-mobile#137]
Generally, the release checklist included targeted days of the week for given tasks, but it is not currently present in the [`gbm` CLI](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/compare/gbm-cli?expand=1).  

> Before the Release **(Tuesday)**

> Create the Release **(Thursday)**

> Integrate the Release **(Thursday)**

**Comment by jhnstn** [comment]
The target dates should appear for scheduled releases but not for patch releases. I have them turned off for the later since patch releases are unscheduled and the specific days are likely inaccurate.

I did just notice that generating the list without a patch value (e.g.`1.98`) does treat the release as "unscheduled".

**Comment by dcalhoun** [comment]
> The target dates should appear for scheduled releases but not for patch releases. I have them turned off for the later since patch releases are unscheduled and the specific days are likely inaccurate.

IIRC this report was also referencing scheduled releases, not unscheduled releases. 

> I did just notice that generating the list without a patch value (e.g.`1.98`) does treat the release as "unscheduled".

Aha, this may be the underlying issue. Relatedly, I do not recall if I typed `1.98.0` or `1.98` when interacting with the CLI. Ideally, either are valid and the required `.0` (its absence breaks correct Git tag/release generation links) is added to all relevant areas. The broken links are referenced in #139.

**Comment by jhnstn** [comment]
> Relatedly, I do not recall if I typed 1.98.0 or 1.98 when interacting with the CLI.

I just tried with `-v 1.98` which the script treats as a valid version. Should be easy enough to imply an intent of `1.98.0` in this case.

**Comment by dcalhoun** [comment]
> > Relatedly, I do not recall if I typed 1.98.0 or 1.98 when interacting with the CLI.
> 
> I just tried with `-v 1.98` which the script treats as a valid version. 

I suppose it is best for me to define what I meant by "valid" to avoid any confusion. Leaving off the `.0` appears to cause issues — lack of target days (https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/issues/137), incorrect release links (https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/issues/139) — and I consider usage of the shorthand (i.e. excluding the `.0`) "invalid" or unsupported until the release script handles those issues appropriately.

**Comment by jhnstn** [comment]
Fixed in https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/pull/146
