### ISSUE TITLE
Add command to prepare GBM release

### ISSUE THREAD

**Issue by jhnstn** [wordpress-mobile/release-toolkit-gutenberg-mobile#152]
The command should
- Update the GB reference to the release tag *
- Prepare the bundle 
- Update the release notes
- Create the release PR

* This is based on the proposal that the prepare GB step will add the release tag.

**Comment by jhnstn** [comment]
What should we do if this command is ran twice? 

It should be reenterant so that if it fails it can be ran again with out causing unexpected behavior i.e. a failed run followed by a successful run should have the same result as a single successful run.

But what should we do if ran after a successful run?
Should it attempt to update or fail? 
In the former case we could add an update flag or have a completely separate update command.

The only redundant work in an update scenario is the PR creation. We should account for this regardless of how we approach updating

**Comment by derekblank** [comment]
* https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/pull/158
