### ISSUE TITLE
CLI: Checklist displays the wrong release date

### ISSUE THREAD

**Issue by jhnstn** [wordpress-mobile/release-toolkit-gutenberg-mobile#156]
The checklist generator shows a suggested message to add to open milestone issues.
It should calculate date for the Thursday following the day the checklist was rendered. 

Currently it's inaccurate. 
The following screenshots were taken after running the script on October 9th. Note that the correct date should be October 12th but was rendered as October 10th.

## Expected
<img width="770" alt="Screenshot 2023-10-09 at 9 22 22 PM" src="https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/assets/744755/e4329eb7-10ce-4ec6-bac7-af42ec0e3679">

## Actual 
<img width="751" alt="Screenshot 2023-10-09 at 9 22 07 PM" src="https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/assets/744755/ad18c123-6d88-4e61-8d3c-4732543873bd">

**Comment by derekblank** [comment]
This would be a good one for me to take.
