### ISSUE TITLE
Integrate GBM prepare package into release command

### ISSUE THREAD

**Issue by derekblank** [wordpress-mobile/release-toolkit-gutenberg-mobile#164]
Integrate the PR preparation from the [gbm.go release package file](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/blob/f90bd9c2d08f890ae8aa527635bb08d1f54ce2d3/cli/pkg/release/gbm.go) into the [prepare.go release command](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/blob/f90bd9c2d08f890ae8aa527635bb08d1f54ce2d3/cli/cmd/release/prepare.go).

**Comment by jhnstn** [comment]
This is fixed by https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/pull/170
