### ISSUE TITLE
Update GBM release pr to include the related changes

### ISSUE THREAD

**Issue by jhnstn** [wordpress-mobile/release-toolkit-gutenberg-mobile#167]
Right now the gbm pr template does not include the "changes" section.

The prior cli prototype does do this but will need to be cleaned up and updated.

Update:
Currently the Pr body ends up empty after running the prepare gbm command

**Comment by jhnstn** [comment]
Here is the [initial prototype template](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/blob/gbm-cli/cli/templates/release/gbmPrBody.md).

It's rendered [here](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/blob/gbm-cli/cli/pkg/release/gbm.go#L111). We should be able to port [`getChangeLog`](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/blob/gbm-cli/cli/pkg/release/gbm.go#L159) and [`getReleaseNotes`](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/blob/gbm-cli/cli/pkg/release/gbm.go#L199) to work with the new code.

**Comment by derekblank** [comment]
Started the initial porting work on a draft PR: https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/pull/183.

**Comment by derekblank** [comment]
Resolved in https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/pull/183
