### ISSUE TITLE
Address Gutenberg Podspec fetching failure

### ISSUE THREAD

**Issue by derekblank** [wordpress-mobile/release-toolkit-gutenberg-mobile#182]
The iOS integration command currently fails when fetching the Gutenberg Podspec:

```
Analyzing dependencies
Pre-downloading: `FSInteractiveMap` from `https://github.com/wordpress-mobile/FSInteractiveMap.git`, tag `0.2.0`
Fetching podspec for `Gutenberg` from `https://cdn.a8c-ci.services/gutenberg-mobile/Gutenberg-v1.11.0.podspec`
[!] Failed to fetch podspec for `Gutenberg` at `https://cdn.a8c-ci.services/gutenberg-mobile/Gutenberg-v1.11.0.podspec`.
 Error: 403 Forbidden
```

**Comment by jhnstn** [comment]
I ran into this when trying to create a "fork" release with a version of GBM that did not exist. 
`v1.11.0` likely exists but predated the recent switch to using the xcframework to package GBM.

I'm thinking we should add a check to see if the `Gutenberg` package exists before continuing.
Also thinking about a `--watch` flag to poll for that before continuing with the ios integration

**Comment by jhnstn** [comment]
I added a check to the `integrate` command to check for published GB builds in [this PR](https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/pull/185/files#diff-7c6debd75d355092d930ab11518508e315ce45190d4bd377124d828eaa70d908)

I'm still not sure how to test this without an open production release. I tried pointing to an old release but all the status checks are gone. Github has been a bit flaky for me so not sure if it's a temporary thing or if the old status checks are deleted after some time after closing the pr.

**Comment by derekblank** [comment]
@jhnstn I believe this issue has been resolved by the two PRs below, and can be moved to the Done column. WDYT? 

- https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/pull/179
- https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/pull/199

**Comment by derekblank** [comment]
Resolved in https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/pull/179 and https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/pull/199
