### ISSUE TITLE
Allow cherry-picking of multiple commits

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/release-toolkit-gutenberg-mobile#36]
The automation script currently allows only one Gutenberg commit to be cherry-picked onto a release. Sometimes we bundle multiple fixes into a betafix/hotfix, so ideally the script would allow for a comma-separated list of hashes (or ask for them one-by-one).

**Comment by mkevins** [comment]
Resolved with: https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/pull/86 :smile:
